using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Backend.Data.Migrations
{
    /// <inheritdoc />
    public partial class UpdateAutoGeneratedId : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "Kartu_keluarga_id",
                table: "AnggotaKartuKeluarga");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<int>(
                name: "Kartu_keluarga_id",
                table: "AnggotaKartuKeluarga",
                type: "int",
                nullable: false,
                defaultValue: 0);
        }
    }
}
