services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: Dukcapil-sql-server-container
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Password21!
      MSSQL_PID: Developer
    ports:
      - "1433:1433"
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
#dibawah untuk comman custom
# services:
#   sql-server:
#     image: mcr.microsoft.com/mssql/server:2022-latest
#     container_name: Dukcapil-sql-server-container
#     environment:
#       - ACCEPT_EULA=Y
#       - MSSQL_SA_PASSWORD=Password21!
#       - MSSQL_PID=Developer
#     ports:
#       - "1433:1433"
#     volumes:
#       - ./init-db.sql:/init-db.sql
#     command: /bin/bash -c "sleep 30 && /opt/mssql-tools18/bin/sqlcmd -U sa -P $$MSSQL_SA_PASSWORD -C -l 30 -e -i /init-db.sql && /opt/mssql/bin/sqlservr"

# services:
#   sql-server:
#     image: mcr.microsoft.com/mssql/server:2022-latest
#     container_name: Dukcapil-sql-server-container
#     environment:
#       ACCEPT_EULA: Y
#       MSSQL_SA_PASSWORD: Password21!
#       MSSQL_PID: Developer
#     ports:
#       - "1433:1433"
# volumes:
#   - ./sql:/docker-entrypoint-initdb.d
# command: /bin/bash -c "until /opt/mssql/bin/sqlservr & sleep 10 && /opt/mssql-tools18/bin/sqlcmd -S localhost -U SA -P 'Password21!' -C -i /docker-entrypoint-initdb.d/init-db.sql; do sleep 1; done"

# mssql:
#   image: mcr.microsoft.com/mssql/server:2017-latest
#   environment:
#     - SA_PASSWORD=Admin123
#     - ACCEPT_EULA=Y
#   volumes:
#    - ./data/mssql:/scripts/
#   command:
#     - /bin/bash
#     - -c
#     - |
#       # Launch MSSQL and send to background
#       /opt/mssql/bin/sqlservr &
#       # Wait 30 seconds for it to be available
#       # (lame, I know, but there's no nc available to start prodding network ports)
#       sleep 30
#       # Run every script in /scripts
#       # TODO set a flag so that this is only done once on creation,
#       #      and not every time the container runs
#       for foo in /scripts/*.sql
#         do /opt/mssql-tools/bin/sqlcmd -U sa -P $$SA_PASSWORD -l 30 -e -i $$foo
#       done
#       # So that the container doesn't shut down, sleep this thread
#       sleep infinity

# services:
# sql-server:
#   image: mcr.microsoft.com/mssql/server:2022-latest
#   container_name: Dukcapil-sql-server-container
#   environment:
#     ACCEPT_EULA: Y
#     MSSQL_SA_PASSWORD: Password21!
#     MSSQL_PID: Developer
#   ports:
#     - "1433:1433"
#   volumes:
#     - ./init-db.sql:/init-db.sql
#   command: >
#     /bin/bash -c "
#       /opt/mssql/bin/sqlservr &
#       sleep 30 &&
#       /opt/mssql-tools18/bin/sqlcmd -S localhost -U SA -P 'Password21!' -C -i /init-db.sql
#     "
