services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: Dukcapil-sql-server-container
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Password21!
      MSSQL_PID: Developer
    ports:
      - "1433:1433"
    # volumes:
    #   - ./sql:/docker-entrypoint-initdb.d
    # command: /bin/bash -c "until /opt/mssql/bin/sqlservr & sleep 10 && /opt/mssql-tools18/bin/sqlcmd -S localhost -U SA -P 'Password21!' -C -i /docker-entrypoint-initdb.d/init-db.sql; do sleep 1; done"
